package:
    name: gridgen
    version: 1.51.2

source:
    git_url: https://github.com/sakov/gridgen-c.git
    git_tag: 7a4a5918e5e2147007cb4830d6f0f24e85db6cba  # upstream does not create releases :-(

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - gridutils
    run:
        - gridutils
        - libgcc

test:
    commands:
        - gridgen -h
        - conda inspect linkages -n _test gridgen  # [linux]

about:
    home: https://github.com/sakov/gridgen-c
    license: Simplified BSD License and triangle.[c,h] license, which is non-free for commercial use
    summary: Non-interactive generation of multi-corner quasi-orthogonal grids inside simply connected polygonal regions

extra:
    recipe-maintainers:
        - ocefpaf
